@startuml
title RO - Register Resource
hide footbox


actor "Resource\nOwner" as RO

box "Resouce Owner Application (ROA)\n<<Custom Application>>" #palegoldenrod
participant "User Interface" as ROAUI
end box

box "Resource Server (RS)\n<<Custom Application>>" #peachpuff
participant "REST API" as RSREST
database "Resource" as RSRESOURCE
database "Credential" as RSCRED
end box

box "Authorization Server (AS)\nForgeRock Access Manager" #antiquewhite
participant "AM API" as AMREST
participant "UMA API" as UMAREST
participant "OAuth API" as OAUTHREST
end box

box "Content Server (CS)\n<<Custom Application>>" #paleturquoise
participant "REST API" as CSREST
database "Data" as CSDATA
end box

RO->AMREST: Authenticate

activate AMREST

AMREST-->RO: Authenticated (SSO Token)

deactivate AMREST

RO->ROAUI: Register Resource

activate ROAUI

ROAUI->RSREST: POST /manage/resources/{id}/register\n(SSO Token)

deactivate ROAUI

activate RSREST

RSREST->AMREST: Validate

deactivate RSREST

activate AMREST

AMREST-->RSREST: 

deactivate AMREST

activate RSREST

RSREST->RSRESOURCE: Read _id

deactivate RSREST

activate RSRESOURCE

RSRESOURCE-->RSREST

deactivate RSRESOURCE

activate RSREST

alt Create PAT if needed

note left of RSREST
A PAT is required to register resource
Either get existing or create one
end note

RSREST->RSREST: GET /manage/pat/{id}

end

RSREST->UMAREST: POST /uma/resource_set

deactivate RSREST

note left of RSREST
Register the resource with the AS
set name, type, allowable scopes
end note

activate UMAREST

UMAREST-->RSREST: 201: _id

deactivate UMAREST

activate RSREST

RSREST->RSRESOURCE: Update _id

note left of RSREST
Update meta data record
registration Id, user_access_policy_uri
Set state to "registered"
end note

deactivate RSREST

activate RSRESOURCE

RSRESOURCE-->RSREST:

deactivate RSRESOURCE

activate RSREST

RSREST-->ROAUI: 201: Created

deactivate RSREST

activate ROAUI

ROAUI-->RO

deactivate ROAUI

@enduml
